apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-nfs-share
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: [INSERT HERE IP OF NFS SERVER]
    path: [INSERT HERE SHARE PATH OF NFS SERVER]